### ISSUE TITLE
Add byte_limit to Emitter

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-python-tracker#170]
This is the same as we do in the Kinesis apps, where it works well.

**Comment by chuwy** [comment]
I think this should be changed to "Add byte_limit to Emitter". I started with refactoring of `Emitter`, adding new `Buffer` object that handles all these three limits, event list and related things, but this refactoring became too big and overengineered. 

Instead: 

1. we always had event-limit (`buffer_size` parameter in `Emitter`)
2. we added time-limit as per https://github.com/snowplow/snowplow-python-tracker/issues/114; 
3. which means we just need to add `byte_limit`. And I think this byte limit should be for python-object-in-memory rather than json-going-to-be-sent-over-network, because stringifying objects just to calculate JSON size would be very ineffective.

@alexanderdean what do you think?

**Comment by alexanderdean** [comment]
Fine by me - @yalisassoon?

**Comment by yalisassoon** [comment]
Good by me!

**Comment by chuwy** [comment]
Cool. Renamed issue
